server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-service
          uri: https://github.com/albertosanchez56/Gestor-de-tareas-con-Microservicios
          search-paths: config-data
  application:
    name: config-service2